### PR TITLE
Adding a #pick(supported, al) method

### PR DESCRIPTION
**Pull request by tlhunter**
* Allows one to easily determine which supported language to reply with
* Semver MINOR

### CODE REVIEW

**Comment by tlhunter** [comment]
@matteofigus

**Comment by matteofigus** [comment]
Thanks for the PR @tlhunter - LGTM but another look from @ArnoldZokas would be appreciated?

**Comment by ArnoldZokas** [comment]
LGTM 👍

**Comment by matteofigus** [comment]
published to 1.1.0

**Pull request merged**
